---
  - name: "include playbook ホスト名を設定"
    include_tasks: set_hostname.yml
    when: 
      - _result_server_parameter.dict[inventory_hostname].csv_hostname != ""

  - name: "include playbook IPv6無効"
    include_tasks: set_disable_ipv6.yml
    when: 
      - _result_server_parameter.dict[inventory_hostname].csv_ipv6 == "No"

  - name: "include playbook OSライセンス認証実施"
    include_tasks: set_activation.yml
    when: 
      - _result_server_parameter.dict[inventory_hostname].csv_product_key != ""

  - name: "include playbook 時刻同期設定"
    include_tasks: set_ntp.yml
    when: 
      - _result_server_parameter.dict[inventory_hostname].csv_peers != ""

  - name: "include playbook IPv4静的IPアドレス変更とデフォルトゲートウェイ変更"
    include_tasks: set_static_ipv4_address.yml
    when: 
      - _result_server_parameter.dict[inventory_hostname].csv_ipv4 != ""
      - _result_server_parameter.dict[inventory_hostname].csv_gateway != ""

  - name: "include playbook DNS設定"
    include_tasks: set_dns.yml
    when: 
      - _result_dns.list|length > 0
      
  - name: "include playbook パスワード変更"
    include_tasks: change_administrator_password.yml
    when: 
      - _result_server_parameter.dict[inventory_hostname].csv_password_local_administrator != ""
...