---
  - win_dns_client:
      adapter_names: "{{ item }}"
      ipv4_addresses: []
    with_items: _adapterlist

  - set_fact:
      _dnslist: "{{ _result_dns.list | map(attribute='csv_dns') | list }}"
    changed_when: False

  - name: "DNSを設定する"
    win_dns_client:
      adapter_names: "{{ item }}"
      ipv4_addresses: "{{ _dnslist }}"
    with_items: _adapterlist
...