---
  - name: Windows Server 2016 を HyperV にデプロイします
    template:
      src: "config_template.j2"
      dest: "library/config.ps1"
      output_encoding: utf_8_sig

  - name: send unattend.xml file
    win_copy:
      src: "unattend.xml"
      dest: "{{ _remote_unattend_file_path }}"

  - name: create vhdx file and new VM.
    script: library/Deploy-WindowsServer.ps1

...