---
  - name: 上位のPlayBookでCSVを読み込んで ROLE で参照できるか？
    debug:
      var: _result_server_parameter.dict

  - name: 上位のPlayBookでCSVを読み込んで ROLE で参照できるか？
    debug:
      msg: "{{ _result_server_parameter.dict[inventory_hostname].csv_workgroup }}"

  - name: 上位のPlayBookでCSVを読み込んで ROLE で参照できるか？
    debug:
      msg: "{{ item.csv_workgroup }}"
    with_items:
      - "{{ _result_server_parameter.dict[inventory_hostname] }}"

  - include_tasks: subtasks.yml

  - name: 読み込んだ DNS CSV の変数置き換え
    set_fact:
      _vlist: "{{ _result_dns.list | map(attribute='csv_dns') | list }}"
  - name: リストへ変換2
    debug:
      var: _vlist

  # Dictionary から List へ変換して、リストを loop させて、値と添え字を取り出す
  - name: 読み込んだ WINS CSV の変数置き換え
    set_fact:
      _winslist: "{{ _result_wins.list | map(attribute='csv_wins') | list }}"
  - name: loop control
    debug:
      msg: "value = {{ item }} index = {{ _wins_index }}"
    loop: "{{ _winslist }}"
    loop_control:
      index_var: _wins_index
...