---
  - name: include される tasks
    debug:
      var: _result_server_parameter.dict

  - name: 上位のPlayBookでCSVを読み込んで ROLE で参照できるか？
    debug:
      msg: "{{ _result_server_parameter.dict[inventory_hostname].csv_workgroup }}"

  - name: 上位のPlayBookでCSVを読み込んで ROLE で参照できるか？
    debug:
      msg: "{{ item.csv_workgroup }}"
    with_items:
      - "{{ _result_server_parameter.dict[inventory_hostname] }}"
...