---
  all:
    hosts:
    children:
      winsvr_host:
        hosts:
          192.168.1.200:
      winsvr_staging:
        hosts:
          192.168.1.203:
      win_test:
        hosts:
          192.168.1.202:
          192.168.1.203:
...