---
# ダウンロードしたファイルから、dotNetFramework3.5 をインストールする
# ダウンロードしたファイルから、dotNetFramework3.5 language pack をインストールする
  - name: "dotNetFramework3.5 インストール済みかどうか？"
    win_shell: Get-WindowsFeature -Name "NET-Framework-Core" | ConvertTo-Json
    register: _result_dotNet35_info

  - set_fact:
      _dot_net_35: "{{ _result_dotNet35_info.stdout }}"

  - name: "dotNetFramework3.5 のインストールファイルをリモートへコピー"
    win_copy:
      src: dotnetfx35.exe
      dest: "{{ remote_temporary_path }}"
    when: _dot_net_35.Installed == false

  - name: "dotNetFramework3.5 言語パッケージをリモートへコピー"
    win_copy:
      src: dotnetfx35langpack_x64ja.exe
      dest: "{{ remote_temporary_path }}"
    when: _dot_net_35.Installed == false

  - name: "dotNetFramework3.5 をインストール"
    win_command: |
      "{{ remote_temporary_path }}"dotnetfx35.exe /PASSIVE /QUIET /NORESTART
    register: _result_install_dotNet35
    when: _dot_net_35.Installed == false

  - name: "dotNetFramework3.5 language pack をインストール"
    win_command: |
      "{{ remote_temporary_path }}"dotnetfx35langpack_x64ja.exe /PASSIVE /QUIET
    register: _result_install_language
    when: _dot_net_35.Installed == false

  - name: "インストール結果の確認"
    win_shell: |
      Get-WindowsFeature -Name "NET-Framework-Core" | ConvertTo-Json
    register: _result_dotNet35_info

  - debug:
      var: _result_dotNet35_info
...