---
  # OS 初期設定
  #- include_tasks: win_ping.yml
  - include_tasks: win_disable_uac.yml
  - include_tasks: win_set_optical_drive_letter.yml
  - include_tasks: win_set_password_policy.yml
  - include_tasks: win_disable_defender.yml
  - include_tasks: win_disable_feedback.yml
  - include_tasks: win_disable_firewall.yml
  - include_tasks: win_disable_ipv6.yml
  - include_tasks: win_set_hostname.yml
  - include_tasks: win_set_ie_esc.yml
  - include_tasks: win_set_ie_proxy_allusers.yml
  - include_tasks: win_set_ie_proxy_user.yml
  - include_tasks: win_set_add_local_intranet.yml
  - include_tasks: win_set_ie_startpage.yml
  - include_tasks: win_set_ntp.yml
  - include_tasks: win_set_winhttp.yml
  - include_tasks: win_set_workgroup.yml
  #- include_tasks: win_set_domain.yml
  - include_tasks: win_visible_desktop_icons.yml
  - include_tasks: win_enable_remote_desktop.yml
  #- include_tasks: win_install_antivirus.yml
  #- include_tasks: win_install_jre8.yml
  #- include_tasks: win_disable_java_update.yml
  - include_tasks: win_set_hidden_shared_folder.yml
  - include_tasks: win_set_static_ipv4_address.yml
  - include_tasks: win_set_dns.yml
  - include_tasks: win_set_wins.yml
  - include_tasks: win_change_administrator_password.yml
  #- include_tasks: win_ping.yml
...