---
    # administrator のパスワードを変更する
    # Ansibleが接続に使用しているユーザーのパスワードを変更するが上手くいっていない
    - name: administrator のパスワードを変更する
      win_user:
        name: administrator
        password: "{{ hv_new_local_adm_psswd }}"
        state: present
...