---
  - name: "インターネットエクスプローラーのスタートページを設定する"
    win_regedit:
      path: HKCU:\Software\Microsoft\Internet Explorer\Main\
      name: start page
      data: "{{ _result_server_parameter.dict[inventory_hostname].csv_startpage }}"
...