---
  - name: ワークグループを設定する
    win_domain_membership:
      workgroup_name: "{{ hv_workgroup_name }}"
      domain_admin_user: "{{ hv_domain_admin_user }}"
      domain_admin_password: "{{ hv_domain_admin_password }}"
      state: workgroup
    register: _result_domain_membership

  - name: do reboot
    win_reboot:
      reboot_timeout: 3600
    when: _result_domain_membership.reboot_required
...