---
  - name: "光学ディスクのドライブレターを変更する"
    win_shell: |
      (Get-Volume | ?{$_.DriveType -match 'CD-ROM'}).driveletter
    register: _result_driveletter

  - name: 光学ドライブのドライブレターを "{{ _result_server_parameter.dict[inventory_hostname].csv_drive_letter }}" に設定する
    win_shell: |
      $driveLetter = "DriveLetter = '" + (Get-Volume | ?{$_.DriveType -match 'CD-ROM'}).driveletter + ":'"
      $drive = Get-WmiObject -Class win32_volume -Filter $driveLetter
      Set-WmiInstance -input $drive -Arguments @{DriveLetter='{{ _result_server_parameter.dict[inventory_hostname].csv_drive_letter }}:'}
    register: _result_ps
    when: 
      - _result_driveletter.stdout_lines|length > 0
      - _result_driveletter.stdout_lines[0] != _result_server_parameter.dict[inventory_hostname].csv_drive_letter
...