---
  - name: "Windows Server 2016 のホスト名を設定する"
    win_hostname: 
      name: "{{ hv_host_name }}"
    register: _result_hostname

  - name: "変更前のホスト名"
    debug:
      msg: "{{ _result_hostname.old_name }}"

  - name: "Windows Server 2016 の再起動"
    win_reboot:
      reboot_timeout: 3600
    when: _result_hostname.reboot_required
...