---
  - name: IE proxy の設定を行う（all users)
    win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\Internet Settings
      name: ProxySettingsPerUser
      data: 0
      type: dword
      state: present

  - name: Configure IE LAN settings
    win_inet_proxy:
      auto_detect: no
      proxy: "{{ gv_proxy }}"
      bypass: "{{ gv_list_bypass }}"
...