---
    # administrator のパスワードを変更する
    # Ansibleが接続に使用しているユーザーのパスワードを変更するが上手くいっていない
    - name: add ansible user
      win_user:
        name: ansible
        password: workinguser%TMP_200819-jp
        groups:
          - Administrators

    - name: switch to ansible user
      set_fact:
        ansible_user: ansible
        ansible_password: workinguser%TMP_200819-jp

    - name: "Administratorのパスワードを変更する"
      win_user:
        name: Administrator
        password: "{{ _result_server_parameter.dict[inventory_hostname].csv_password_local_administrator }}"
        state: present

    - name: change user
      set_fact:
        ansible_user: Administrator
        ansible_password: "{{ _result_server_parameter.dict[inventory_hostname].csv_password_local_administrator }}"

    - name: delete ansible user
      win_user:
        name: ansible
        state: absent
...