---
  - name: インストール CLAMWIN アンチウイルスソフト
    win_copy:
      src: "{{ _local_path }}"
      dest: "{{ _remote_path }}"
    register: _result_file_cpy

  - name: silent install
    win_command: |
      "{{ _remote_path }}" /sp- /silent /norestart
    when: _result_file_cpy.operation == "file_copy"

  - name: clean up installer file in tmp directory
    win_file:
      path: "{{ _remote_path }}"
      state: absent
...
