---
  - name: 共有隠しフォルダの設定
    win_file:
      path: "{{ _result_server_parameter.dict[inventory_hostname].csv_shared_folder }}"
      state: directory

  - name: 共有隠しフォルダの設定を行う
    win_share:
      name: apps$
      description: created hidden shared folder by ansible
      path: "{{ _result_server_parameter.dict[inventory_hostname].csv_shared_folder }}"
      list: no
      full: Administrator,everyone
      state: present
...