---
  - name: 疎通確認と facts の収集
    win_ping:
      data: "pong"

  - name: get windows server informations
    debug: 
      var: ansible_facts
  - name: systeminfo command
    win_command: systeminfo
    register: _result_info
  - name: display system information
    debug: 
      var: _result_info
...