---
  # Windows defender を完全に無効にする
  - name: Windows defender を完全に無効にする
    win_shell: Get-WindowsFeature Windows-Defender* | Where-Object {$_.InstallState -eq 'Installed'}
    register: _result_query

  - name: Windows Defender をアンインストール
    win_shell: Uninstall-WindowsFeature -Name Windows-Defender
    register: _resutl_uninstall
    when: _result_query.stdout != ""

  - name: OS を再起動する
    win_reboot:
      reboot_timeout: 3600
    when: _resutl_uninstall.changed == true
...