---
    # administrator のパスワードを変更する
    # Ansibleが接続に使用しているユーザーのパスワードを変更するが上手くいっていない
    - name: パスワード変更を実行するユーザを追加する
      win_user:
        name: ansible
        password: workinguser%TMP_200819-jp
        groups:
          - Administrators

    - name: パスワード変更を実施するユーザに接続を変える
      set_fact:
        ansible_user: ansible
        ansible_password: workinguser%TMP_200819-jp

    - name: Administratorのパスワードを変更する
      win_user:
        name: Administrator
        password: "{{ _result_server_parameter.dict[inventory_hostname].csv_password_local_administrator }}"
        state: present

    - name: 接続ユーザーを元に戻す
      set_fact:
        ansible_user: Administrator
        ansible_password: "{{ _result_server_parameter.dict[inventory_hostname].csv_password_local_administrator }}"

    - name: パスワード変更用ユーザを削除する
      win_user:
        name: ansible
        state: absent
...