---
  - name: "ワークグループを設定する"
    win_domain_membership:
      workgroup_name: "{{ _result_server_parameter.dict[inventory_hostname].csv_workgroup }}"
      domain_admin_user: "{{ ansible_user }}"
      domain_admin_password: "{{ ansible_password }}"
      state: workgroup
    register: _result_domain_membership

  - name: "OS を再起動する"
    win_reboot:
      reboot_timeout: 3600
    when: _result_domain_membership.reboot_required
...