---
  - name: ホストに到達できなかった場合次来た時に再接続できるようにエラーフラグをクリアする
    meta: clear_host_errors

  - name: ログファイル名のサフィックス（日時）を取得
    local_action: command date +%Y%m%d%H%M%S
    register: _result_local_action

  - name: Windows Update を実行する
    win_updates:
      category_names:
        - Application
        - Connectors
        - CriticalUpdates
        - DefinitionUpdates
        - DeveloperKits
        - FeaturePacks
        - Guidance
        - SecurityUpdates
        - ServicePacks
        - Tools
        - UpdateRollups
        - Updates
      log_path: "{{ remote_temporary_path }}ansible_win_update_{{ inventory_hostname }}_{{ _result_local_action.stdout }}.log"
      server_selection: windows_update
      state: installed
    register: _result_win_update

  - name: Windows Update の結果
    debug:
      var: _result_win_update
      verbosity: 0

  - name: サーバーからログファイルを収集する
    fetch:
      src: "{{ remote_temporary_path }}ansible_win_update_{{ inventory_hostname }}_{{ _result_local_action.stdout }}.log"
      dest: "{{ local_logfile_path }}"
      flat: yes

  - name: Windows Update が一つも行われなかったので終了する
    meta: end_host
    when: not _result_win_update.changed

  - name: 再起動が必要な場合は行う
    win_reboot:
      reboot_timeout: 3600
    when: _result_win_update.reboot_required
...