---
  - name: Get a datetime for logfile name
    local_action: command date +%Y%m%d%H%M%S
    register: _result_local_action

  - name: Do Windows Update
    win_updates:
      category_names:
        - Application
        - Connectors
        - CriticalUpdates
        - DefinitionUpdates
        - DeveloperKits
        - FeaturePacks
        - Guidance
        - SecurityUpdates
        - ServicePacks
        - Tools
        - UpdateRollups
        - Updates
      log_path: "C:\\tmp\\ansible_win_update_{{ inventory_hostname }}_{{ _result_local_action.stdout }}.log"
      server_selection: windows_update
      state: installed
    register: _result_win_update

  - name: Debug display update results
    debug:
      var: _result_win_update
      verbosity: 0

  - name: Get a win_update log file from a remote Windows server.
    fetch:
      src: "C:\\tmp\\ansible_win_update_{{ inventory_hostname }}_{{ _result_local_action.stdout }}.log"
      dest: "{{ _local_logfile_path }}"
      flat: yes

  - meta: end_host
    when: not _result_win_update.changed

  - name: reboot if needed
    win_reboot:
      reboot_timeout: 3600
    when: _result_win_update.reboot_required
...