---
  # https://docs.microsoft.com/en-us/powershell/module/addsdeployment/install-addsforest?view=win10-ps
  # DomainMode, ForestMode
  # Windows Server 2003  : 2 or Win2003
  # Windows Server 2008  : 3 or Win2008
  # Windows Server 2008R2: 4 or Win2008R2
  # Windows Server 2012  : 5 or Win2012
  # Windows Server 2012R2: 6 or Win2012R2
  # Windows Server 2016  : 7 or WinThreshold
  _ad_opts:
    DomainName: ad01.local
    SafeModeAdministratorPassword: Ansible_201208    # SafeModeAdministratorPasswordで指定するパスワードは「ディレクトリ復元モード」時にのみ使用するために新しく作るパスワードであり、従来のAdministatorユーザのものではない
    CreateDnsDelegation: $False
    DatabasePath: 'C:\Windows\NTDS'
    DomainMode: 'WinThreshold'
    DomainNetbiosName: ADANSIBLE
    ForestMode: 'WinThreshold'
    InstallDns: $True
    LogPath: 'C:\Windows\NTDS'
    NoRebootOnCompletion: $False
    SysvolPath: 'C:\Windows\SYSVOL'
    Force: $True
...